name: Deploiment continue

on:
  push:
    branches:
      - main
      - release

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      REACT_APP_API_URL: "https://pokeapi.co/api/v2/pokemon/"

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy staging
        if: github.ref == 'refs/heads/release'
        run: echo "Deploying to staging"
        # Here you should add your deployment steps for staging

      - name: Deploy production
        if: github.ref == 'refs/heads/main'
        run: echo "Deploying to production"
        # Here you should add your deployment steps for production
