name: CI/CD Pipeline

on: 
  push:
    branches : 
      - main # Déclenché à chaque nouveau commit sur le main
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Install dependencies
        run: npm i
     
      - name: Install Babel plugin proposal private property in object
        run: npm install --save-dev @babel/plugin-proposal-private-property-in-object

      - name: Debug Environment Variables
        run: printenv | grep REACT_APP_API_URL

      - name: Build
        env:
          CI: false  # Ignorer les erreurs ESLint dans le cadre de la construction
        run: npm run build

      - name: Test
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_API_MOVE_URL: ${{ secrets.REACT_APP_API_MOVE_URL }}
        run: npm run test -- --watchAll=false  # Exécute les tests une fois et arrête le processus

      - name: Check test result
        if: success()  # Si les tests ont réussi
        run: |
          echo "Test validé"
          git checkout release && git merge main --no-ff --no-edit && git push origin release
          echo "Merge de la branche en production validé"

      - name: Check test failure
        if: failure()  # Si une étape précédente a échoué
        run: echo "Tests échoués !"
