name: Integration continue

on: 
  push:
    branches : 
      - main
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Install dependencies
        run: npm i

      - name: Build
        env:
          CI: false  # Ignorer les warnings ESLint dans le cadre de la construction
        run: npm run build

      - name: Test
        run: npm run test
